[package]
name = "hs_dbscan"
version = "1.0.2"
edition = "2024"

[lib]
name = "hs_dbscan"

[dependencies]
nalgebra = "0.34.1"
rand = "0.9.2"
rand_distr = "0.5.1"
criterion = "0.8.1"
strum = "0.27.2"
strum_macros = "0.27.2"
rstest = "0.26.1"
approx = "0.5.1"
indexmap = "2.12.1"
rapidhash = "4.2.0"
serde = "1.0.228"
serde_json = "1.0.148"
eyre = "0.6.12"
dataviz = { version = "0.1.9", optional = true }

[features]
visualize = ["dep:dataviz"]

[[bench]]
name = "benchmarks"
harness = false

[[bin]]
name = "plotter"
path = "src/bin/plotter.rs"
required-features = ["visualize"]